Hotfix backend getprofile
2110423-2019-2/sec33_Matcher pull request #47
Opened 2020-03-27 19:54 UTC by daidew

- get user profile by session id (/profile/)
- get user profile by custom id (/profile/abc....xyz)

2020-03-28 13:40 UTC, nisaruj requested changes
Format code ด้วย

2020-03-28 13:40 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +                throw new HttpErrors.BadRequest();
`HttpErrors.NotFound()`

2020-03-28 13:40 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +        if(typeof(req.params.userId) === 'undefined'){
ใช้ `!(req.params.userId)` น่าจะ save กว่า

https://repl.it/@nisaruj/ShockedTrimTrapezoids

2020-03-28 13:40 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +            if(req.params.userId.toString().length !== 24){
จริงๆไม่ต้องเช็คก็ได้นะ 555 ยังไงก็ NotFound อยู่แล้ว และเผื่อเปลี่ยน id ในอนาคตจะได้ไม่บึ้ม

2020-03-28 13:40 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +            res.json({
จริงๆเราเขียนรองรับส่วน find user by id ไว้ละ ตรง `getUserProfile()`
แต่ทำตรงนี้เลยดีกว่า แต่ขอให้มีพฤติกรรมเหมือน `getUserProfile()` คือมี field score ด้วย

2020-03-28 13:40 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +            if(req.user._id.toString() !== id.toString()){
mongoose มี method .equals ใช้เทียบ Object ID กับ string ได้ เช่น `req.user._id.equals(id)`

2020-03-28 13:40 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +                console.log(req.user._id, id);
ลบออกด้วย อิอิ

2020-03-28 14:47 UTC, daidew commented on Backend/src/controllers/user.controller.ts
> +            res.json({
ตายละ พึ่งเห็นว่ามี getUserProfile แล้ว555  ถ้างั้นเอาไงดีอะ รวมไว้ในฟังก์ชั่นเดียวปะ ใช้ชื่อ getProfile หรือ getUserProfile ดี

2020-03-28 14:48 UTC, nisaruj commented on Backend/src/controllers/user.controller.ts
> +            res.json({
รวมๆ เอาเป็น getProfile ของไดก็ได้

2020-03-29 12:33 UTC, nisaruj approved these changes
lgtm

2020-03-29 12:33 UTC, merged